// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"l01mco0vq8","name":"ReactSample","description":"","endpoint":"https://l01mco0vq8.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/items","/items/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:fbf0df5a-75e0-4076-b9ea-e52b8852cec9',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'hercone-hosting-mobilehub-153994528',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1mew6189ozetn.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-east-1',
    'aws_dynamodb_table_schemas': [{"tableName":"hercone-mobilehub-153994528-bbq_menu_item","attributes":[{"name":"restaurant_id","type":"S"},{"name":"id","type":"S"}],"indexes":[],"region":"us-east-1","hashKey":"restaurant_id","rangeKey":"id"},{"tableName":"hercone-mobilehub-153994528-bbq_orders","attributes":[{"name":"id","type":"S"}],"indexes":[],"region":"us-east-1","hashKey":"id"},{"tableName":"hercone-mobilehub-153994528-bbq_restaurants","attributes":[{"name":"id","type":"S"}],"indexes":[],"region":"us-east-1","hashKey":"id"}],
    'aws_project_id': 'ae1c25dc-4ab8-4df6-9c11-88643fadeaaf',
    'aws_project_name': 'hercone',
    'aws_project_region': 'us-east-1',
    'aws_resource_bucket_name': 'hercone-deployments-mobilehub-153994528',
    'aws_resource_name_prefix': 'hercone-mobilehub-153994528',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_qTjlBCNnZ',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '5mde9k6os959hsh2jnq15jijia',
}

export default awsmobile;
