// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"0jl8r6ytha","name":"barInf","description":"","endpoint":"https://0jl8r6ytha.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/bars","/bars/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:f0e40134-54a1-47b0-b297-d895a1e5a4ca',
    'aws_cognito_region': 'us-east-1',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-east-1',
    'aws_dynamodb_table_schemas': [{"tableName":"hercone-mobilehub-1541391316-bars","attributes":[{"name":"barID","type":"N"},{"name":"agid","type":"N"},{"name":"barSerial","type":"N"},{"name":"dateProc","type":"S"},{"name":"dateRec","type":"S"},{"name":"manufacturer","type":"S"},{"name":"mint","type":"S"},{"name":"purity","type":"N"},{"name":"rfid","type":"N"},{"name":"supplier","type":"S"},{"name":"weight","type":"N"}],"indexes":[],"region":"us-east-1","hashKey":"barID"}],
    'aws_project_id': '3051244e-ef38-465c-a047-363061d038ae',
    'aws_project_name': 'hercone',
    'aws_project_region': 'us-east-1',
    'aws_resource_bucket_name': 'hercone-deployments-mobilehub-1541391316',
    'aws_resource_name_prefix': 'hercone-mobilehub-1541391316',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'hercone-userfiles-mobilehub-1541391316',
    'aws_user_files_s3_bucket_region': 'us-east-1',
    'aws_user_settings': 'enable',
}

export default awsmobile;
